---
driver:
  name: vagrant
  linked_clones: true
  gui: false
  communicator: winrm
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: dsc

transport:
  name: winrm

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: windows-2016-standard
    driver:
      box: tragiccode/windows-2016-standard
      gui: true
      # network: 
      #   - ["forwarded_port", {guest: 80, host: 8080}]
    provisioner:
      dsc_local_configuration_manager_version: wmf5
suites:
  - name: CreateHTTPListener
    provisioner:
      configuration_script_folder: Examples/Resources
      configuration_script: xWinRMListener/1-CreateHTTPListener.ps1