---
driver:
  name: vagrant
  linked_clones: true
  gui: false
  communicator: winrm
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: dsc

transport:
  name: winrm

verifier:
  name: pester
  test_folder: Tests/Integration

platforms:
  - name: windows-2016-standard
    driver:
      box: tragiccode/windows-2016-standard
      gui: true
    provisioner:
      dsc_local_configuration_manager_version: wmf5
suites:
  - name: MSFT_xWinRMListener
    provisioner: 
      configuration_script_folder: Tests/Integration/MSFT_xWinRMListener
      configuration_script: MSFT_xWinRMListener.config.ps1
      configuration_name: CreateHttpListener