
version: 1.0.{build}-{branch}
os: Windows Server 2012 R2

build: off

install:
  - ps: |
        Find-Package Pester | Install-Package -SkipValidate
        Find-Package xDSCResourceDesigner | Install-Package -SkipValidate

test_script:
    - ps: |
          Invoke-Pester -Path .\Tests\Unit -OutputFile ".\TestResults.xml" -OutputFormat NUnitxml -CodeCoverage .\DSCResources\*

deploy_script:
- ps: |
      if($env:APPVEYOR_REPO_BRANCH -eq "masterdddd") {

        # Extract version from changelog

        # Update the xWinRM.psd1 extracted version

        # commit & tag
        
        Publish-Module -NuGetApiKey $env:PSGalleryApiKey -Path $env:APPVEYOR_BUILD_FOLDER -Confirm:$false;
        
        git config --global credential.helper store
        Add-Content "$env:USERPROFILE\.git-credentials" "https://${env:GitHubKey}:x-oauth-basic@github.com`n"
        
        git tag $env:APPVEYOR_BUILD_VERSION
        git push origin -q $env:APPVEYOR_BUILD_VERSION
      } 

notifications:
  - provider: Slack
    incoming_webhook:
      secure: oYviEmkGtgAO8Ij90h3s60tvql2KDBmHGkL7YHb1HAdd2hlEHsC36Xkew7Ei01nUsI7ZfcvbbjDCu+lImrHOpl4Jcmvd5lsZL9k1bhxup7Q=
    channel: general
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false